# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test .NET using a matrix

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    # prevent failed job to block entire workflow and other jobs
    continue-on-error: true

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        dot-net-version: [6.0.x, 7.0.x]
        exclude:
          - os: ubuntu-latest
            dot-net-version: 7.0.x

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dot-net-version }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
